[package]
name = "minimal-ffi-repro"
version = "0.1.0"
authors = ["capage"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Current (latest) version of dioxus/manganis
dioxus = {version = "0.8.0-alpha.0"}
manganis = { version = "0.8.0-alpha.0"}

# My local patched version
#dioxus = { path = "../dioxus/packages/dioxus", version = "0.8.0-alpha.0"}
#manganis = { path = "../dioxus/packages/manganis/manganis", version = "0.8.0-alpha.0"}


[features]
default = ["mobile"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
