[application]

[web.app]

[bundle]
identifier = "com.example.minimalffirepro"

# HTML title tag content
title = "minimal-ffi-repro"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[android]
min_sdk = 24
target_sdk = 34